---
- name: copy zookeeper package to dest server
  copy: src={{repos}}/{{zookeeper_pkg}} dest={{cloud_root}}/{{zookeeper_pkg}}

- name: extract archive to dest cloud home dir
  command: chdir=/usr/share /bin/tar xzf {{cloud_root}}/{{zookeeper_pkg}} -C {{cloud_root}} creates={{zookeeper_home}}

- name: copy configure files to zookeeper server
  template: src={{item}}.j2 dest={{zookeeper_home}}/conf/{{item}} 
  with_items:
  - zoo.cfg

- name: create zookeeper data dir
  file: path={{zookeeper_data_dir}} state=directory 

- name: create zookeeper id
  shell: echo {{zoo_id}} > {{zookeeper_data_dir}}/myid

- include: ../../services/tasks/start_zookeeper.yml 
  

