---
#- name: create the data directory for the namenode metadata
#  file: path={{dfs_namenode_name_dir}} state=directory 

- name: format namenode
  shell: export JAVA_HOME={{java_home}};export PATH=$PATH:{{java_home}}/bin;sleep 60;{{hadoop_home}}/bin/hadoop namenode -format;sleep 60

- include: ../../services/tasks/start_namenode.yml
#- name: start namenode service
#  shell: export JAVA_HOME={{java_home}};export PATH=$PATH:{{java_home}}/bin:{{hadoop_home}}/sbin;
#         sh hadoop-daemon.sh start namenode;
#         sh hadoop-daemon.sh start journalnode;
#         sh hadoop-daemon.sh start zkfc;
#         sh yarn-daemon.sh start resourcemanager

