---
- name: start flume services
  shell: export JAVA_HOME={{java_home}};export PATH=$PATH:{{java_home}}/bin;cd {{flume_home}}; bin/flume-ng agent --conf ./conf --f conf/flume-conf.properties --name a1 -Dflume.root.logger=DEBUG,LOGFILE &